# Generated by Django 3.2.8 on 2021-11-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы от кандидатов'},
        ),
        migrations.AddField(
            model_name='application',
            name='is_watch',
            field=models.BooleanField(default=False),
        ),
    ]
