# Generated by Django 3.2.9 on 2021-11-09 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media_rezume')),
                ('position_applied_for', models.CharField(max_length=55)),
                ('num_passport_expire', models.CharField(max_length=55)),
                ('full_name', models.CharField(max_length=55)),
                ('nationality_gender', models.CharField(max_length=55)),
                ('country_city_of_residence', models.CharField(max_length=55)),
                ('date_and_place_of_birth', models.CharField(max_length=55)),
                ('age_height_weight', models.CharField(max_length=30)),
                ('status_children', models.CharField(max_length=30)),
                ('health_smoker', models.CharField(max_length=30)),
                ('image_full_height', models.ImageField(upload_to='media_rezume')),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=55)),
                ('period_city_country', models.CharField(max_length=55)),
                ('responsibilities', models.TextField()),
                ('personal_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal_data')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_professional_achievements_skills', models.TextField()),
                ('work_time', models.CharField(choices=[('1', 'Less than 40 hours/week'), ('2', '40–50 hours/week'), ('3', 'More than 50 hours/week')], max_length=30)),
                ('i_confirm_that_the_information_of_application_form_is_true', models.CharField(max_length=5)),
                ('personal_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.personal_data')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('E', 'English'), ('R', 'Russian'), ('T', 'Turkish'), ('A', 'Arabic'), ('C', 'Chinese')], max_length=10)),
                ('written', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('spoken', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('understanding', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('personal_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal_data')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=10)),
                ('year_of_graduation_city_country', models.CharField(max_length=55)),
                ('personal_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.personal_data')),
            ],
        ),
    ]
